# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CRUD_PC2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CRUD_PC2

pod 'DropDown'
pod 'Toaster'

end
